# Site
lang: "en"
title: "Simple Template"
author: "Ankit R Gadiya"
url: "https://st.argp.in"
baseurl: ""
logo: "https://github.com/simple-template.png"
remote_theme: simple-template/jekyll

# Build
timezone: Asia/Kolkata
markdown: kramdown
